### PR TITLE
add block type mapping

### PR DESCRIPTION
**Pull request by viviloaf**
Added a dictionary of Minecraft block types

### CODE REVIEW

**Comment by hydrostaticcog** [comment]
I’m not against merging this, but I want to know whether we should add this infrastructure now or whenever we add world functionality?

**Review by hydrostaticcog — CHANGES_REQUESTED** [review]
If we do add this, this list is incomplete. You should include all the block IDs and their names in this list.

**Review by Geolykt — CHANGES_REQUESTED** [review]
The PR in the current state is almost useless. As far as I know this system has been deprecated since at least 1.13 and the keys are no longer used anywhere (feel free to prove me wrong there).

Furthermore such data shouldn't be hardcoded but rather parsed from the minecraft-data repository (that is a submodule of the current repo now thanks to #63 )

So basically this PR should be converted to work in a way that it will solve at least one point within #39

**Comment by Geolykt** [comment]
> I’m not against merging this, but I want to know whether we should add this infrastructure now or whenever we add world functionality?

It's best to merge such things beforehand, since they will more or less be needed there

**Comment by viviloaf** [comment]
Oh, I didn't know that a system to parse data already existed in #63

I'll have a look at the issue in #39 and revise this PR

**Review by hydrostaticcog — CHANGES_REQUESTED** [review]
Blocks are already parsed by `classes/utils/DataParser.py`. You could expand on that there as @Geolykt said, and you can use the data there for world generation and whatnot.

**Pull request closed without merging**
