### PR TITLE
Fix MacOS formatting Error (part 2 ?)

### LINKED ISSUE #72: Not logging chat message
**Bug Description**
Chat is not being logged by logging import

**To Reproduce**
1. Send Text in Minecraft
2. No logging for message

**Expected behaviour**
As in the code `logging.info(message)` in Connection.py its expected to be logged as info

**Host system:**
 - MacOS
 - Big Sur (X86)
 - Python 3.8.5 64-bit

### PR DESCRIPTION
**Pull request by hydrostaticcog**
This PR aims to fix the formatting (or lack thereof) on MacOS systems.

The `format` option, and the `debug` logging level override have been causing some issues, so I have removed them and just set the main logging level in `main.py`

Resolves #72

### CODE REVIEW

**Review by Geolykt — CHANGES_REQUESTED** [review]
This would basically remove the debug flag, not entirely sure if that is any good. As such I'm a bit torn on this.

**Comment by hydrostaticcog** [comment]
Does the debug flag currently do anything other than change the logging level?

**Comment by Geolykt** [comment]
Not that I know

**Comment by hydrostaticcog** [comment]
If that's the case, it should probably just be removed.

**Comment by hydrostaticcog** [comment]
I have removed the debug flag, as it was only causing problems. Although, with the continued issues with MacOS, we should probably consider dropping support for it entirely.

**Review by Geolykt — APPROVED** [review]
We should filter out uses of the debug log later on, but in the current state it is good for a merge

**Pull request merged**
