### PR TITLE
Consistent logging and allow users to set the logging format

### LINKED ISSUE #57: Inconsisent log formatting
**Describe the bug**
the startup.py file uses a different logging format than the rest of the project

**To Reproduce**
1. Run `python3 startup.py`

**Expected behavior**
Uniform logging format

**Host system:**
 - OS: Fedora
 - OS version: 33 (Kernel version 5.10.9-201.fc33.x86_64)
 - Python version: 3.9.1

**Additional context**
Current output is:
```
INFO:root:Making sure pip is installed...
Defaulting to user installation because normal site-packages is not writeable
Looking in links: /tmp/tmp4e2vgybv
Requirement already up-to-date: setuptools in /usr/lib/python3.9/site-packages (49.1.3)
Requirement already up-to-date: pip in /usr/lib/python3.9/site-packages (20.2.2)
INFO:root:Installed.
INFO:root:Getting release list...
INFO:root:McPy found! Running it...
root | INFO | Trying to initialize the Blackfire probe
root | INFO | Blackfire not installed: passing
root | INFO | Starting queues...
root | INFO | Started queues!
root | INFO | Trying to find number of available cores
root | INFO | Found 2 cores available!
root | INFO | Starting worker ID 84619
root | INFO | Started worker.
root | INFO | Worker ID 84619 has started up.
root | INFO | Starting networking worker
root | INFO | Started worker.
root | INFO | Startup done! Listening on 0.0.0.0:25565
^Croot | INFO | Shutting server down!
root | INFO | Worker ID 84619 has completed all tasks.
Traceback (most recent call last):
  File "/home/Geolykt/git/McPy/startup.py", line 174, in <module>
    mcpyProcess = subprocess.check_call(data)
  File "/usr/lib64/python3.9/subprocess.py", line 368, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python3.9/subprocess.py", line 351, in call
    return p.wait(timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1185, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib64/python3.9/subprocess.py", line 1915, in _wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib64/python3.9/subprocess.py", line 1873, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterrupt

```

### PR DESCRIPTION
**Pull request by Geolykt**
Fairly small change. Also "fixes" some inconsistencies across platforms while the main goal was to fix inconsistencies across startup.py (now dependencies.py) and main.py

Resolves #57

### CODE REVIEW

**Review by hydrostaticcog — APPROVED** [review]
Looks good!

**Review by ntoskrnl4 — APPROVED** [review]

**Comment by hydrostaticcog** [comment]
As far as I know, there is not enough active GitHub users here with write access to this repo for the 2 approving reviews requirement.

**Comment by Geolykt** [comment]
Correct, as unforunately I cannot approve my own PR we will have to wait for @tazz4843

**Review by tazz4843 — APPROVED** [review]
Looks fine

**Pull request merged**
